name: 'Setup Docker Test Environment'
description: 'Setup standardized Docker test environment for various test types'
author: 'NextJS Boilerplate Team'

inputs:
  test-type:
    description: 'Type of test (unit|integration|e2e|all)'
    required: true
  enable-testcontainers:
    description: 'Enable Testcontainers configuration'
    required: false
    default: 'false'
  create-directories:
    description: 'Create test result directories'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64
        
    - name: Setup base environment files
      shell: bash
      run: |
        echo "Setting up environment files for test type: ${{ inputs.test-type }}"
        
        # Copy base environment files
        cp .env.base.example .env.base
        cp .env.test.example .env.test
        cp .env.test .env.local
        
        # Add Docker-specific configurations
        echo "DOCKER_HOST=unix:///var/run/docker.sock" >> .env.local
        
    - name: Configure for Testcontainers
      if: inputs.enable-testcontainers == 'true'
      shell: bash
      run: |
        echo "Configuring Testcontainers support..."
        echo "TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal" >> .env.local
        
    - name: Configure for E2E tests
      if: inputs.test-type == 'e2e'
      shell: bash
      run: |
        echo "Configuring E2E test environment..."
        echo "BASE_URL=http://app-server:3000" >> .env.local
        echo "PLAYWRIGHT_SKIP_WEBSERVER=true" >> .env.local
        
    - name: Create test directories
      if: inputs.create-directories == 'true'
      shell: bash
      run: |
        echo "Creating test result directories..."
        mkdir -p test-results coverage playwright-report
        
    - name: Display environment summary
      shell: bash
      run: |
        echo "🔧 Docker Test Environment Setup Complete"
        echo "  Test Type: ${{ inputs.test-type }}"
        echo "  Testcontainers: ${{ inputs.enable-testcontainers }}"
        echo "  Directories Created: ${{ inputs.create-directories }}"
        echo "  Environment files: .env.base, .env.test, .env.local"